django_movies/accounts/urls.py
from django.urls import path

from accounts.views import SignUpView, SubmittableLoginView, SuccessMessagedLogoutView, SubmittablePasswordChangeView


app_name = 'accounts'

urlpatterns = [
    path('login/', SubmittableLoginView.as_view(), name='login'),
    path('logout/', SuccessMessagedLogoutView.as_view(), name='logout'),
    path('password-change/', SubmittablePasswordChangeView.as_view(), name='password_change'),
    path('sing-up/', SignUpView.as_view(), name='sign_up'),
]

django_movies/django_movies/urls.py
from django.contrib import admin
from django.urls import path, include

from films_dict.views import MovieCreateView, MovieListView, MovieUpdateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MovieListView.as_view(), name='index'),
    path("films_dict/", include('films_dict.urls', namespace='films_dict')),
    path("accounts/", include('accounts.urls', namespace='accounts')),


]

django_movies/films_dict/urls.py
from django.urls import path


from films_dict.views import MovieCreateView, MovieUpdateView, MovieDeleteView

from films_dict.views import MovieListView, MovieDetailView

app_name = 'films_dict'
urlpatterns = [
    path('movie/list', MovieListView.as_view(), name='movie_list'),
    path('movie/detail/<pk>', MovieDetailView.as_view(), name='movie_detail'),
    path('movie/create', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<pk>', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>', MovieDeleteView.as_view(), name='movie_delete'),

]

django_movies/films_dict/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from model_utils import Choices

AGE_LIMIT_CHOICES = Choices(
    (0, 'kids', 'Kids'),
    (1, 'teens', 'Teens'),
    (2, 'adults', 'Adults'),
)


class Genre(models.Model):
    name = models.CharField(max_length=20, unique=True)

    age_limit = models.IntegerField(null=True, blank=True, choices=AGE_LIMIT_CHOICES)

    def __str__(self):
        return str(self.name)


class Director(models.Model):
    first_name = models.CharField(max_length=50)
    second_name = models.CharField(max_length=50)

    class Meta:
        unique_together = ('first_name', 'second_name')

    def __str__(self):
        return f"{self.first_name} from {self.second_name}"


class Country(models.Model):
    countries_name = models.CharField(max_length=100)

    def __str__(self):
        return self.countries_name


class Movie(models.Model):
    title = models.CharField(max_length=100)
    rating = models.IntegerField(
        null=True, validators=[MaxValueValidator(10), MinValueValidator(1)]
    )
    released = models.DateField()
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    genre = models.ForeignKey(Genre, null=True, on_delete=models.DO_NOTHING)
    director = models.ForeignKey(Director, null=True, on_delete=models.DO_NOTHING)
    countries = models.ManyToManyField(Country, related_name="movies")

    class Meta:
        unique_together = ('title', 'released')

    def __str__(self):
        return f"{self.title} from {self.released}"

django_movies/films_dict/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit
from django import forms
from django.core.exceptions import ValidationError
from films_dict.models import Genre, Movie, Director, Country
import re
from datetime import date


def capitalized_validator(value):
    if value[0].islower():
        raise ValidationError('Value must be capitalized.')


def validate_len_name(value):
    if len(value) > 25:
        raise ValidationError('So long film title')


class PastMonthField(forms.DateField):
    def validate(self, value):
        super().validate(value)
        if value >= date.today():
            raise ValidationError('Only past dates allowed here.')

    def clean(self, value):
        result = super().clean(value)
        return date(year=result.year, month=result.month, day=1)


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

    title = forms.CharField(validators=[capitalized_validator])
    rating = forms.IntegerField(min_value=1, max_value=10)
    released = PastMonthField()
    genre = forms.ModelChoiceField(queryset=Genre.objects.all())
    created = forms.DateTimeField()
    director = forms.ModelChoiceField(queryset=Director.objects.all())
    description = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'title',
            Row(Column('rating'), Column('released'), Column('created'), Column('genre')),
            'director', 'description',
            Submit('submit', 'Submit')

        )

    def clean_description(self):
        initial = self.cleaned_data['description']
        sentences = re.sub(r'\s*\.\s*', '.', initial).split('.')
        cleaned = '.'.join(sentence.capitalize() for sentence in sentences)
        return cleaned

    def clean(self):
        result = super().clean()
        if result['genre'].name == 'comedy' and result['rating'] > 5:
            raise ValidationError('The best comedy is worth a 4.')
        return result

django_movies/films_dict/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, FormView, CreateView, UpdateView, DeleteView, DetailView
from films_dict.models import Movie, AGE_LIMIT_CHOICES, Genre

from films_dict.forms import MovieForm


class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


def hello(request):
    return render(
        request,
        template_name="hello.html",
        context={'adjectives': ['beautiful', 'cruel', 'wonderful']}
    )


class MovieListView(ListView):
    template_name = "movie_list.html"
    model = Movie


class MovieDetailView(LoginRequiredMixin, DetailView):
    template_name = "movie_detail.html"
    model = Movie


class GenreView(ListView):
    template_name = "genres.html"
    model = Genre

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['AGE_LIMIT_CHOICES'] = Genre.objects.all()
        return context


LOGGER = logging.getLogger()


class MovieCreateView(LoginRequiredMixin, CreateView):
    template_name = 'form.html'
    form_class = MovieForm
    success_url = reverse_lazy('index')

    '''def form_valid(self, form):
        result = super().form_valid(form)
        cleaned_data = form.cleaned_data
        Movie.objects.create(
            title=cleaned_data['title'],
            genre=cleaned_data['genre'],
            rating=cleaned_data['rating'],
            released=cleaned_data['released'],
            description=cleaned_data['description'],
        )
        return result '''

    def form_invalid(self, form):
        LOGGER.warning('Invalid data provided')
        return super().form_invalid(form)


class MovieUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    title = 'Update Movie'
    template_name = 'form.html'
    model = Movie
    form_class = MovieForm
    success_url = reverse_lazy('films_dict:movie_list')

    def form_invalid(self, form):
        LOGGER.warning('Invalid data provided')
        return super().form_invalid(form)


class MovieDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    title = 'Delete Movie'
    template_name = 'movie_confirm_delete.html'
    model = Movie
    form_class = MovieForm
    success_url = reverse_lazy('films_dict:movie_list')

django_movies/films_dict/templates/base.html
{% load bootstrap4 %}
{% load static %}

<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>

  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Django Movies</title>
      {% block styles %}{% bootstrap_css %}{% endblock %}
      {% block scripts %}{% bootstrap_javascript jquery='full' %}{% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container fixed">
<!--        <a class="navbar-brand" href="/">Django Movies</a> bezposredni link!!!-->
        <a class="navbar-brand" href="{% url 'index' %}">Django Movies</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/">
              Home
            </a>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>

</html>

django_movies/films_dict/templates/genres.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to Django Movies!</h1>
    <h2>Films Genre:</h2>
    <ul>
            {% for genre in object_list %}
                <li>
                    {{ genre }}
                </li>
            {% endfor %}
    </ul>
{% endblock %}

django_movies/films_dict/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello, world!</title>
</head>
<body>
    <h1>Hello, my friend...</h1>
    {% for adjective in adjectives %}
        {% if adjective != "cruel" %}
            <p>This is a {{ adjective }} world...</p>
        {% endif %}
    {% endfor %}
</body>
</html>

django_movies/films_dict/templates/movie_confirm_delete.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>
        Are you sure you want to delete movie "{{ object.title }}" from database?
    </p>
    <input type="submit" value="Yes" class="btn btn-danger">
</form>
{% endblock %}

django_movies/films_dict/templates/movie_detail.html
{% extends "base.html" %}

{% load movie_extras %}

{% block content %}
  {{ movie|attr_as_p:'title' }}
  {{ movie|attr_as_p:'rating' }}
  {{ movie|attr_as_p:'released' }}
  {{ movie|attr_as_p:'description' }}
  {{ movie|attr_as_p:'genre' }}
  {{ movie|attr_as_p:'created' }}
  {{ movie|attr_as_p:'director' }}

{% endblock %}

django_movies/films_dict/templates/movie_list.html
{% extends "base.html" %}
{% load movie_extras %}
{% block content %}
  <ul>
    {% for movie in object_list %}
      <li>
        {% movie_format movie short=True %}
        <a href="{% url 'films_dict:movie_detail' movie.pk %}">detail</a> /
        <a href="{% url 'films_dict:movie_update' movie.pk %}">update</a> /
        <a href="{% url 'films_dict:movie_delete' movie.pk %}">delete</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

django_movies/films_dict/templates/movies.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to Django Movies!</h1>
    <ul>
            {% for movie in object_list %}
                {% if movie.genre.age_limit != limits.adults %}
                <li>
                    {{ movie.title }} ({{ movie.released.year }}) by {{movie.director}}, genre: {{movie.genre.name}}
                </li>
                {% endif %}
            {% endfor %}
    </ul>
{% endblock %}